schemaVersion: "1"
agent: claude
workspace: .

kits:
  # AI tools
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=rtk/claude"
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=ccstatusline"
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=i-have-adhd/claude"
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=caveman/claude"
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=mattpocock-skills/claude"

  # Dev environment tools
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=pnpm"
  - "git+https://github.com/ZYCGary/sbx-kits.git#dir=laravel-sail"

secrets:
  github:
    command: gh auth token --user mathsonline-gary

ports:
  - sandbox: 3000
